---
title: "HRaDeX Report"
author: ""
date: ""
output:
  html_document:
  theme: united
highlight: textmate
toc: true
toc_float: true
number_sections: false
df_print: paged
params:
  dat_params: list()
dat_summary: data.frame()
input_info: list()
components: list()
---
  
  <style type="text/css">
  span { 
    display: block;
    max-width: 100%;
    word-wrap: break-word;
  }
</style>
  
Report generated on `r Sys.time()` using the [HRaDeXGUI](http://github.com/hadexversum/HRaDeXGUI) R package, interface
to the [HRaDeX](http://github.com/hadexversum/HRaDeX) package.

# Data summary

Protein name: `r dat()[["Protein"]][1]`

State: `r fit_state()`

# Selected parameters 

Workflow: `r workflow_type()`

Control: `r fit_control()`

Class definition: 

```{r echo = FALSE}
fit_k_params()
```

# Analysis

```{r echo = FALSE}
cat(fit_info_txt())
```

```{r echo = FALSE, results = "asis", warning = FALSE, message = FALSE}
hires_plot()
```

```{r echo = FALSE, results = "asis", warning = FALSE, message = FALSE}
plot_cov_class_plot_out()
```

```{r echo = FALSE, results = "asis", warning = FALSE, message = FALSE}
gridExtra::grid.arrange(plot_n_plot_out(), plot_rss_hist_plot_out(), nrow = 1)
```

